Repository AaronSadlerUK/Umbraco.MegaNavV8, pull requests merged in 2020-11, with the labels that each got.

#16 Add support for no udi in json (migrated from v7).
  src/AaronSadler.MegaNavV8.Core/ValueConverters/MeganavV8ValueConverter.cs
Labels: bug, enhancement

#19 6 Collapse all doesn't collapse child elements
  TestSite/App_Plugins/MeganavV8/Js/meganavv8.controller.js
  TestSite/App_Plugins/MeganavV8/Views/editor.html
  src/AaronSadler.MegaNavV8.Web/Web/UI/App_Plugins/MeganavV8/Js/meganavv8.controller.js
  src/AaronSadler.MegaNavV8.Web/Web/UI/App_Plugins/MeganavV8/Views/editor.html
Labels: enhancement

#20 6 Collapse all doesn't collapse child elements
  TestSite/App_Plugins/MeganavV8/Js/meganavv8.controller.js
  src/AaronSadler.MegaNavV8.Web/Web/UI/App_Plugins/MeganavV8/Js/meganavv8.controller.js
Labels: bug

#21 8 Add ability to disable content sync
  TestSite/Web.config
  src/AaronSadler.MegaNavV8.Core/AppSettingsManager.cs
  src/AaronSadler.MegaNavV8.Core/ValueConnectors/MeganavV8ValueConnector.cs
Labels: enhancement

#24 Feature - add/re-add drag threshold to the angular-ui-tree component
  TestSite/App_Plugins/MeganavV8/Js/angular-ui-tree.js
  src/AaronSadler.MegaNavV8.Web/Web/UI/App_Plugins/MeganavV8/Js/angular-ui-tree.js
Labels: enhancement
